/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Eventos: () => import('#controllers/eventos_controller'),
  Inscricaos: () => import('#controllers/inscricaos_controller'),
  Participantes: () => import('#controllers/participantes_controller'),
  Profile: () => import('#controllers/profile_controller'),
}
