/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = [
    'abilities',
    'createdAt',
    'expiresAt',
    'hash',
    'id',
    'lastUsedAt',
    'name',
    'tokenableId',
    'type',
    'updatedAt',
  ] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class EventoSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'dataFinal',
    'dataInicio',
    'descricao',
    'id',
    'idOrganizador',
    'local',
    'nome',
    'updatedAt',
  ] as const
  $columns = EventoSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare dataFinal: DateTime
  @column.dateTime()
  declare dataInicio: DateTime
  @column()
  declare descricao: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare idOrganizador: number
  @column()
  declare local: string
  @column()
  declare nome: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class InscricoeSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'idEvento', 'idParticipante', 'updatedAt'] as const
  $columns = InscricoeSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare idEvento: number
  @column()
  declare idParticipante: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ParticipanteSchema extends BaseModel {
  static $columns = ['createdAt', 'dataNasc', 'email', 'id', 'nome', 'senha', 'updatedAt'] as const
  $columns = ParticipanteSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare dataNasc: DateTime
  @column()
  declare email: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare nome: string | null
  @column()
  declare senha: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
